
name: echo


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo Hello, world!
      -  name : etc
         run: ls /etc
      -  name: etc
         run: ls -a /etc

